# Paramètres du modèle
model:
  hidden_channels: 64

# Paramètres de l'entraînement
training:
  epochs: 100
  learning_rate: 0.002
  weights_path: "weights/st_graph_sage_v1.pth"

# Paramètres des données
data:
  sequence_length: 48

# Paramètres de l'analyse d'anomalies
analysis:
  anomaly_threshold: 0.2