# Paramètres du modèle
model:
  in_channels: 4
  hidden_channels: 64
  out_channels: 4

# Paramètres de l'entraînement
training:
  epochs: 1000
  learning_rate: 0.005
  weights_path: "weights/st_graph_sage_v1.pth"

# Paramètres des données
data:
  sequence_length: 24 # Longueur de la séquence (e.g., 48 x 30 min = 24h)

# Paramètres de l'analyse d'anomalies
analysis:
  anomaly_threshold: 0.002